SYSTEM_NAME="gog"
SYSTEM_FULLNAME="GOG"
SYSTEM_MANUFACTURER="GOG"
SYSTEM_RELEASE="System"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/gog/"
SYSTEM_EXTENSION=".sh"
SYSTEM_PLATFORM="gog"
SYSTEM_THEME="gog"
SYSTEM_WIKI_PATH="gog"
